version: '3'
services:
  redis:
    container_name: redis
    image: redislabs/redismod
    ports:
      - 6379:6379
  redisinsight:
    container_name: redisinsight
    image: redislabs/redisinsight:latest
    ports:
      - '8001:8001'
    volumes:
      - /Users/jason/data/redisinsight:/db
      - /Users/jason/data/redisinsight/prod-20211122.rdb:/home/prod-20211122.rdb
